import type { Item } from './types';

/** 14 seed items for the demo — posted_by_user_id is null (system/demo data) */
export const SEED_ITEMS: Omit<Item, 'id' | 'created_at'>[] = [
  // ── LOST ──────────────────────────────────────────────────
  {
    type: 'lost',
    title: 'Black Leather Wallet',
    category: 'Wallet',
    description: 'Lost my black leather wallet near the library. It had my student ID, bank cards, and some cash inside. Slim bifold style.',
    location: 'Central Library, 2nd Floor',
    date: '2026-05-10',
    image_url: null,
    color: 'Black',
    brand: 'No brand',
    identifying_details: 'Has a small "R" monogram inside and a torn corner on the card slot.',
    contact_name: 'Rahul Sharma',
    contact_email: 'rahul.sharma@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Rahul Sharma',
    status: 'open',
  },
  {
    type: 'lost',
    title: 'Student ID Card — Ananya Mehta',
    category: 'ID Card',
    description: 'Lost my college ID card near the cafeteria. Card number 2024-CSE-087. Has my photo and department name.',
    location: 'Main Cafeteria',
    date: '2026-05-11',
    image_url: null,
    color: 'Blue',
    brand: null,
    identifying_details: 'Lanyard attached — red and white striped.',
    contact_name: 'Ananya Mehta',
    contact_email: 'ananya.mehta@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Ananya Mehta',
    status: 'open',
  },
  {
    type: 'lost',
    title: 'AirPods Pro Case',
    category: 'Earbuds / Headphones',
    description: 'Lost my white AirPods Pro charging case in the lecture hall during the morning session. No earbuds inside, just the case.',
    location: 'Lecture Hall B-204',
    date: '2026-05-12',
    image_url: null,
    color: 'White',
    brand: 'Apple',
    identifying_details: 'Small scratch on the lid, custom sticker of a blue wave on the back.',
    contact_name: 'Omar Khan',
    contact_email: 'omar.khan@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Omar Khan',
    status: 'open',
  },
  {
    type: 'lost',
    title: 'Blue Water Bottle',
    category: 'Water Bottle',
    description: 'Lost my blue steel water bottle near the sports complex after evening practice. 750ml, has a black flip lid.',
    location: 'Sports Complex, Ground Floor',
    date: '2026-05-09',
    image_url: null,
    color: 'Blue',
    brand: 'Milton',
    identifying_details: 'Has my name "Priya" written in black marker on the bottom.',
    contact_name: 'Priya Nair',
    contact_email: 'priya.nair@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Priya Nair',
    status: 'open',
  },
  {
    type: 'lost',
    title: 'Scientific Calculator',
    category: 'Stationery',
    description: 'Left my calculator in the engineering block after the numerical methods exam. Black calculator with orange buttons.',
    location: 'Engineering Block, Room E-101',
    date: '2026-05-08',
    image_url: null,
    color: 'Black',
    brand: 'Casio',
    identifying_details: 'Model fx-991EX. Sticker with roll number 21CS047 on the back.',
    contact_name: 'Rahul Sharma',
    contact_email: 'rahul.sharma@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Rahul Sharma',
    status: 'open',
  },
  {
    type: 'lost',
    title: 'Spiral Notebook — Algorithms',
    category: 'Books / Notebooks',
    description: 'Lost my blue spiral notebook with algorithms notes near the bus stop. First few pages have my name and phone number.',
    location: 'Campus Bus Stop, Gate 2',
    date: '2026-05-13',
    image_url: null,
    color: 'Blue',
    brand: null,
    identifying_details: 'Name "Ananya" written on the cover, doodles on the back.',
    contact_name: 'Ananya Mehta',
    contact_email: 'ananya.mehta@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Ananya Mehta',
    status: 'open',
  },
  {
    type: 'lost',
    title: 'Key Bunch with Bike Key',
    category: 'Keys',
    description: 'Lost a bunch of keys near the parking area. Has a bike key, room key, and a small padlock key. Red keychain.',
    location: 'Student Parking Area, Block C',
    date: '2026-05-12',
    image_url: null,
    color: 'Red',
    brand: null,
    identifying_details: 'Red carabiner keychain with a small blue rubber duck charm.',
    contact_name: 'Omar Khan',
    contact_email: 'omar.khan@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Omar Khan',
    status: 'open',
  },

  // ── FOUND ─────────────────────────────────────────────────
  {
    type: 'found',
    title: 'Found: Black Wallet Near Library',
    category: 'Wallet',
    description: 'Found a black bifold wallet near the library entrance. Has some cards inside. Handover at security desk.',
    location: 'Central Library, Entrance',
    date: '2026-05-10',
    image_url: null,
    color: 'Black',
    brand: null,
    identifying_details: 'Has cards and a monogram initial inside.',
    contact_name: 'Priya Nair',
    contact_email: 'priya.nair@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Priya Nair',
    status: 'open',
  },
  {
    type: 'found',
    title: 'Found: Student ID Near Cafeteria Counter',
    category: 'ID Card',
    description: 'Found a student ID card on the floor near the cafeteria billing counter. Name visible on the card.',
    location: 'Main Cafeteria, Billing Counter',
    date: '2026-05-11',
    image_url: null,
    color: 'Blue',
    brand: null,
    identifying_details: 'CSE department card, has a red and white lanyard.',
    contact_name: 'Rahul Sharma',
    contact_email: 'rahul.sharma@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Rahul Sharma',
    status: 'open',
  },
  {
    type: 'found',
    title: 'Found: Earbuds Case in Lecture Hall',
    category: 'Earbuds / Headphones',
    description: 'Found a white earbuds charging case under a seat in the lecture hall. Looks like AirPods. Kept with the professor.',
    location: 'Lecture Hall B-204',
    date: '2026-05-12',
    image_url: null,
    color: 'White',
    brand: 'Apple',
    identifying_details: 'Has a sticker on the lid.',
    contact_name: 'Ananya Mehta',
    contact_email: 'ananya.mehta@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Ananya Mehta',
    status: 'open',
  },
  {
    type: 'found',
    title: 'Found: Blue Water Bottle Near Gym',
    category: 'Water Bottle',
    description: 'Found a blue steel water bottle outside the gym entrance. Name written on the bottom in marker.',
    location: 'Sports Complex, Gym Entrance',
    date: '2026-05-09',
    image_url: null,
    color: 'Blue',
    brand: 'Milton',
    identifying_details: 'Name written on bottom, black flip lid.',
    contact_name: 'Omar Khan',
    contact_email: 'omar.khan@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Omar Khan',
    status: 'open',
  },
  {
    type: 'found',
    title: 'Found: Casio Calculator in Classroom',
    category: 'Stationery',
    description: 'Found a Casio scientific calculator left on a desk in Room E-101 after an exam. Roll number sticker on back.',
    location: 'Engineering Block, Room E-101',
    date: '2026-05-08',
    image_url: null,
    color: 'Black',
    brand: 'Casio',
    identifying_details: 'Roll number sticker on the back.',
    contact_name: 'Priya Nair',
    contact_email: 'priya.nair@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Priya Nair',
    status: 'open',
  },
  {
    type: 'found',
    title: 'Found: Spiral Notebook at Bus Stop',
    category: 'Books / Notebooks',
    description: 'Found a blue spiral notebook at the bus stop bench. Has a name on the cover and detailed CS notes.',
    location: 'Campus Bus Stop, Gate 2',
    date: '2026-05-13',
    image_url: null,
    color: 'Blue',
    brand: null,
    identifying_details: 'Name on cover, doodles on back.',
    contact_name: 'Rahul Sharma',
    contact_email: 'rahul.sharma@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Rahul Sharma',
    status: 'open',
  },
  {
    type: 'found',
    title: 'Found: Keychain Near Parking',
    category: 'Keys',
    description: 'Found a set of keys with a red carabiner and a small charm near parking Block C. Submitted to campus security office.',
    location: 'Student Parking Area, Block C',
    date: '2026-05-12',
    image_url: null,
    color: 'Red',
    brand: null,
    identifying_details: 'Red carabiner, small rubber duck charm.',
    contact_name: 'Ananya Mehta',
    contact_email: 'ananya.mehta@campus.edu',
    posted_by_user_id: null,
    posted_by_name: 'Ananya Mehta',
    status: 'open',
  },
];
